name: Render CV

run-name: CI pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Compile-Linux-GNU:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Bootstrap and render
          run: |
            sudo apt update
            sudo apt install python3 python3-pip texlive-base
            ./bootstrap.sh
            ./render.sh

        - name: Release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: false
            prerelease: false
            release_name: Release ${{ github.sha }}
            tag_name: v${{ github.sha }}
            body: CV updated
          env:
            GITHUB_TOKEN: ${{ github.token }}

        - name: Upload CV PDF
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./rendercv_output/Egor_Demidov_CV.pdf
            asset_name: Egor_Demidov_CV.pdf
            asset_content_type: application/pdf

  #      - name: Archive compiled artifact
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: soot-dem-linux-gnu-x86_64
  #          path: |
  #            dist