name: Render CV

run-name: CI pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Compile-Linux-GNU:
      runs-on: ubuntu-latest
      container:
        image: reitzig/texlive-base:2024.8
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Bootstrap
          run: |
            sudo apt install python3
            ./bootstrap.sh
  #      - name: Archive compiled artifact
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: soot-dem-linux-gnu-x86_64
  #          path: |
  #            dist